owncloud/mail

lib/controller/accountscontroller.php
Fixes https://github.com/owncloud/mail/issues/418
=> Require no admin permissions for auto-completion

js/mail.js
Meanwhile we do it already in core...
Partially fixes https://github.com/owncloud/mail/issues/425
=> Don't double encode

appinfo/application.php, lib/controller/messagescontroller.php, lib/service/autoconfig.php, lib/service/logger.php
I added a simple log wrapper using dependency injection
=> DI logging added

js/views/message.js
same as https://github.com/owncloud/mail/pull/431
@LukasReschke are those parameters double encoded as well?
=> remove double encoding

js/views/message.js
=> do not unmark active message on refresh

js/mail.js
=> hide 'Load More' button if message count smaller than pagination limit

tests/service/htmltest.php
=> add url detection test

lib/controller/accountscontroller.php
There was a typo of a variable, ref #444
=> Fix undefined variable 'name'

lib/controller/pagecontroller.php
To make HTML mails work again in Owncloud 8.1
=> Fix Content Security Policy for frame-src

css/mail.css, templates/index.php
@Xenopathic @wurstchristoph please review. :)
=> ellipsize account names in sidebar/settings to fix overflow, fix #446

templates/index.php
Just some tiny fixes, please review @DeepDiver1975 @wurstchristoph
=> fix wording and capitalization

lib/message.php
Don't trust the remote server to decode the MIME transfer type, it doesn't work for Dovecot at least. Instead, decode the body part ourselves, like attachments get decoded.
With this, I can now read base64 transfer encoded emails!
Fixes #399
=> Correctly decode transfer encoding on message body

js/mail.js
```setFolderInactive``` removed as it is not necessary anymore
fixes #440
=> highlight only one folder at a time

lib/controller/proxycontroller.php
=> NoCSRFRequired on ProxyController::proxy()

lib/attachment.php, lib/controller/messagescontroller.php, lib/mailbox.php
=> Fixing download of attachments where the filename is within the content-type and not the content-disposition 

css/mail.css, js/mail.js, templates/index.php
@mikelupe I rebased your original pull request https://github.com/owncloud/mail/pull/391 and also fixed the design. :)
@zinks- @PoPoutdoor @DeepDiver1975 @wurstchristoph please review
=> Dropdown selection added for IMAP & SMTP security config

js/send-mail.js, js/views/sendmail.js
Please review @DeepDiver1975 @wurstchristoph
=> simplify sent feedback, didn't show cc anyway

js/mail.js, js/views/message.js, lib/controller/messagescontroller.php, lib/mailbox.php, templates/index.php
=> Implement search

appinfo/application.php, lib/controller/messagescontroller.php, lib/message.php
=> Use to as from in sent folders - fixes #342

.travis.yml, lib/account.php, lib/mailbox.php, tests/imap/abstracttest.php, tests/imap/accounttests.php
=> Starting functional tests against a GMail account

js/send-mail.js, js/views/sendmail.js
implements https://github.com/owncloud/mail/issues/491
=> send mails by using ctrl+enter

js/send-mail.js, js/views/sendmail.js
@wurstchristoph fixes the issue you mentioned in https://github.com/owncloud/mail/issues/99#issuecomment-93816187
=> fix send/reply button being disabled again after sending a message

lib/controller/messagescontroller.php
Please review @DeepDiver1975 @wurstchristoph
=> also show '& others' when message had people in cc

appinfo/application.php, js/compose.js, js/mail.js, js/send-mail.js, js/settings.js, js/views/message.js, js/views/sendmail.js, lib/service/autoconfig.php, tests/imap/accounttests.php
I tried to fix a bunch of the issues reported by [Scrutinizer](https://scrutinizer-ci.com/g/owncloud/mail/issues/master):
* coding style
* unused code
* JS bugs
The rest I am not knowledgeable enough about, especially the PHP stuff.
Please review @DeepDiver1975 @LukasReschke @wurstchristoph
=> fix a bunch of issues reported by Scrutinizer

lib/controller/accountscontroller.php
=> log why sending a new mail failed

js/jquery.storageapi.js, js/mail.js, templates/index.php
=> Caching accounds and folders

templates/index.php
=> Set type of user inputs to text instead of email - fixes #520

README.md
Fix #519 please review @Henni @LEDfan
=> add cache reset instructions to readme, fix #519

js/mail.js
Reference to the currently loading request is kept in Mail.State and aborted if another folder is loaded.
TextStatus from the $.ajax error handler is trickled down to prevent handling it as a real error.
EDIT: changed the PR name to something more explicit ;)
=> Don't load multiple folders at once

lib/account.php, lib/mailbox.php, lib/message.php, lib/service/autoconfig.php, lib/service/html.php
@DeepDiver1975 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/owncloud/mail/
=> Scrutinizer Auto-Fixes

lib/controller/accountscontroller.php
=> Fix undefined variable error

appinfo/app.php, appinfo/application.php, lib/account.php, lib/controller/accountscontroller.php, lib/service/autoconfig.php, tests/imap/abstracttest.php
fixes #244
**PLEASE TRUNCATE YOUR DATABASE ENTRIES**
=> Store password encrypted

js/mail.js
=> handle 400 responses returned while creating a new account

js/mail.js
=> don't cache for the time being

.travis.yml, lib/account.php, tests/imap/abstracttest.php
This fixed all failed tests.
Please be aware that this pr is towards uid-validity branch in #522.
On top of this, please set `Concurrent jobs` to 1 on travis-ci.org.
=> #522 Fix uid validity branch

js/mail.js
Fix for #529 
Always using the same SendMail view instance seems to fix the problem.
However, I am not sure if it should be stored in Mail.State or Mail.UI ?
@jancborchardt @DeepDiver1975 @wurstchristoph and others:) Please review
=> Fix multiple sending of messages

composer.json, composer.lock, lib/account.php, lib/mailbox.php, tests/imap/abstracttest.php, tests/imap/accounttest.php
fixed non-ascii mailbox name
#522 #444 
@DeepDiver1975 @jancborchardt
=> #522 non-ascii mailbox name

lib/account.php, lib/mailbox.php
I'm not so sure about the coding style, but this sure fixed the problem. Fix #444 (Cannot connect to Gmail account)
=> fix getSpecialFolder(), ref #444

css/mail.css, js/mail.js, templates/index.php
Better design for:
* initial mail account connection
* empty mail folders
* no search results
Only thing left to do: Hide `#app-navigation` and `#app-navigation-toggle` on first time setup. But only when no account is configured yet. Please help @DeepDiver1975
=> Style empty content messages

css/mail.css, css/mobile.css
Fix https://github.com/owncloud/mail/issues/328, please review @RandolfCarter @owncloud/designers @wurstchristoph @irgendwie @Henni @Gomez
=> make header bar scroll instead of fixed, fix #328

js/mail.js
=> 10 seconds timeout

js/mail.js, js/send-mail.js, js/views/sendmail.js, templates/compose.php, templates/index.php
=> Use oc notification on send

css/mail.css
Yeah I know @colmoneill maybe CSS preprocessing wouldn’t be such a bad idea. ;)
Please review @wurstchristoph @irgendwie @zinks- @Gomez
=> fix opacity & shading of several icons

lib/controller/messagescontroller.php, lib/message.php
=> Fix to and reply fields in sent folders

appinfo/routes.php, js/mail.js, js/send-mail.js, js/views/message.js, js/views/sendmail.js, lib/account.php, lib/controller/accountscontroller.php, lib/controller/messagescontroller.php, lib/mailbox.php, lib/message.php, templates/index.php
=> save and open drafts

js/views/message.js, lib/account.php, lib/controller/messagescontroller.php, templates/index.php
=> Expunge mails from the trash

js/mail.js, js/views/message.js
=> Clear search on folder change

js/views/message.js
Please review @wurstchristoph @Gomez @irgendwie
=> fix wording of check messages, fix #595

README.md
Please review @DeepDiver1975 @Gomez @wurstchristoph @zinks- everyone. :)
=> add 'why is this so awesome' section, fix contributor list

lib/account.php, lib/mailbox.php
- fixes #553
@jancborchardt @wurstchristoph
=> Allow delete of messages in our special fav folder

templates/index.php
=> prefill cc field

templates/index.php
Before 
After
Please review @Gomez @irgendwie @wurstchristoph
=> fix whitespace between cc list and closing parenthesis

js/send-mail.js, js/views/sendmail.js
fix #562
Please review @clementhk @colmoneill @Xenopathic @Gomez! :)
=> autosize textarea on send, fix #562

css/mail.css, templates/index.php
Add link pointing to Mailvelope so people can use encrypted emails. Please review @DeepDiver1975 @toberndo @uggrock
=> add Mailvelope link to settings

js/mail.js
=> show message content again after clicking a folder when adding a new account

.jshintignore, .jshintrc, .travis.yml, js/mail.js, js/send-mail.js, js/settings.js, js/views/folder.js, js/views/message.js, package.json
This adds npm & jshint to travis and fixes the js problems.
@DeepDiver1975 @jancborchardt
=> Add jshint Testing

templates/index.php
Now you can hover over the title when it’s ellipsized to show the full title.
Please review @DeepDiver1975 @wurstchristoph @Gomez @irgendwie @Xenopathic @zinks- :)
=> add title attribute to subject so it can be shown when it overflows

js/views/message.js
=> Stop unread counter from decrementing if star / unstar messages.

js/mail.js, templates/index.php
=> use handlebars to change css class of the currently opened folder

js/mail.js, lib/account.php
=> Dont show empty notifications

js/mail.js, js/models/attachment.js, js/views/folder.js, lib/account.php, lib/mailbox.php
=> Such an ugly hack - fixes #611

js/views/message.js, lib/account.php, lib/message.php
Attempt to fix https://github.com/owncloud/mail/issues/634 but it doesn’t quite work.
What am I doing wrong @DeepDiver1975 @Xenopathic?
=> mark deleted message as read, fix #634

README.md
=> Changed from 0.1 to 0.2

.travis.yml
https://github.com/owncloud/mail/pull/653/files?w=1
=> Update the branches.only setting in .travis.yml

lib/controller/pagecontroller.php
Simple change, please review @enoch85 @irgendwie @zinks- everyone :)
=> remove empty and unneeded compose.css file

js/mail.js
should fix #659 (very ugly, but functional :see_no_evil:)
I debugged a few hours and it seems like there is a race condition,
if interested I can explain at the next meetup in munich.
I'm too lazy to write a full description of the problem here.
@enoch85 @wurstchristoph please review!
also cc @jancborchardt @DeepDiver1975
=> fix opening first mailbox.

README.md
Please check if this is understandable @enoch85 @Gomez @clementhk thanks! :)
=> add installation section to readme

appinfo/application.php, lib/account.php, lib/attachment.php, lib/controller/accountscontroller.php, lib/controller/folderscontroller.php, lib/controller/messagescontroller.php, lib/controller/pagecontroller.php, lib/controller/proxycontroller.php, lib/db/mailaccount.php, lib/db/mailaccountmapper.php, lib/hordetranslationhandler.php, lib/http/attachmentdownloadresponse.php, lib/http/proxydownloadresponse.php, lib/mailbox.php, lib/message.php, lib/searchmailbox.php, lib/service/autoconfig.php, lib/service/contactsintegration.php, lib/service/html.php
- short array syntax
- double emtpy lines
- opening curly braces
- unused use statements
- space indents
=> coding style improvements

js/mail.js
fixes #684 
@irgendwie @jancborchardt
=> abort previous message load request

css/mail.css, templates/index.php
Please review @wurstchristoph @Xenopathic @Henni @irgendwie :)
=> 'position: fixed' for new message button, fix #681

lib/mailbox.php
As talked about in https://github.com/owncloud/mail/issues/411#issuecomment-103142914, please review @MeCias @DeepDiver1975 @zinks-
=> add 'sentmail' to special folders detection

js/mail.js
The delete keyboard shortcut will delete the currently active message.
Fixes: #670
=> Added a delete hot key.

js/mail.js, lib/message.php
It's work in progress, but should already work for text messages.
Edit: PR for #648 @jancborchardt
=> Inline reply functionality

lib/account.php, lib/attachment.php, lib/mailbox.php, lib/message.php, lib/searchmailbox.php, lib/service/html.php
=> fix some Scrutinizer issues

CONTRIBUTING.md
Additionally, I added some parts of the newer CONTRIBUTOR.md file of the core repository
@DeepDiver1975 @jancborchardt @zinks-
=> remove contributor agreement

js/mail.js
=> Abort message loading when the composer is being shown

lib/service/contactsintegration.php
@enoch85 please have a look - THX
Fixes #656
=> Fix undefined index - fixes #656

lib/mailbox.php
fixes #663 
@DeepDiver1975 @enoch85
=> filter deleted mails

lib/message.php, tests/data/mail-message-123.txt, tests/messagetest.php
I had issues with displaying of email from codacy because of some character in the html body which could not be converted to utf-8 .
unit test included
@LukasReschke @irgendwie @zinks- @wurstchristoph please review - THX
=> Fix iconv issue and allow proper display of some html messages

js/mail.js, js/views/sendmail.js
=> show OC notification when draft was saved successfully

.jscsrc, js/settings.js
This adds the jscs config file with sane defaults. I formatted the settings.js. 
See #631
=> Adds JSCS - and formats settings js

js/compose.js
Another one. 
@DeepDiver1975 @wurstchristoph @clementhk @Xenopathic Get it in...
=> JSCS for compose.js

js/views/attachment.js
@DeepDiver1975 @wurstchristoph @clementhk @Xenopathic Last one for today
=> JSCS for attachment.js

css/mail.css, js/mail.js, js/views/message.js, lib/message.php, templates/index.php
=> Open composer from an email address in message view

js/mail.js, js/views/folder.js, js/views/message.js
=> client-side message cache

js/send-mail.js
One more file.
209 errors to go
=> JSCS for send-mail.js

js/views/folder.js
Just some spacing and quoting
@DeepDiver1975 @wurstchristoph @clementhk @Xenopathic
=> JSCS for folder.js

js/views/message.js
Fixed delete function.
Fixed message loading function.
Modified delete function to load a newer message upon deletion, otherwise load an older message upon deletion.
Resolves issues #730 and #753
=> Fixed message deletion bug, and message loading.

js/views/message.js
Fix for bug #614.
Seems like it's a jQuery bug?!
@wurstchristoph @jancborchardt review please!
=> Fix tipsy not shown for next message in trash

css/mail.css, css/mobile.css, js/mail.js, js/views/message.js, templates/index.php
Please review @owncloud/designers @DeepDiver1975 @wurstchristoph @aidanamavi @colmoneill 
This is only the first pass, making the view work on mobile. What has to be done in follow-up PRs is to also show the actions like delete and favorite in the detail view.
=> make Mail app work on mobile again, fix #457

.gitignore, .jscsrc, Gruntfile.js, package.json
usage: "grunt jscs"
https://github.com/jscs-dev/grunt-jscs/
@Gomez review please :)
=> add grunt task for running jscs checks

js/mail.js, templates/index.php
=> prefill cc from draft if set

js/mail.js, js/send-mail.js, js/views/sendmail.js
As mail.js is mostly spaghetti code, I started refactoring a little bit and added js object properties where they make sense (Mail.State, Mail.UI).
Additionally, I changed all ``function (..`` occurrences to ``function(..``.
@aidanamavi @colmoneill  @DeepDiver1975 @irgendwie @jancborchardt please review ;-)
=> properties added + code formatted

lib/controller/messagescontroller.php
=> Fix saving attachments to files

css/mobile.css, js/mail.js
Please review @Henni @irgendwie :)
=> fix some mobile details

js/mail.js
fixes #573 
@Xenopathic @jancborchardt @aidanamavi please review
=> resize iframe on window resize

js/mail.js
First work in progress to fix #710 – not tested yet. :) cc @colmoneill @aidanamavi @DeepDiver1975 if you wanna check it out.
=> special notification layout if there is only 1 new message, fix #710

lib/account.php, lib/cache/cache.php, lib/controller/accountscontroller.php, lib/controller/messagescontroller.php, lib/controller/pagecontroller.php, lib/controller/proxycontroller.php, lib/db/mailaccount.php, lib/db/mailaccountmapper.php, lib/http/attachmentdownloadresponse.php, lib/http/htmlresponse.php, lib/mailbox.php, lib/searchmailbox.php, lib/service/autoconfig.php
Made little autists crazy when their IDE is always yellow
@jancborchardt Please review. (just merge - that's enough :speak_no_evil:)
=> Fix PHPDoc

js/mail.js, js/send-mail.js, js/views/sendmail.js
Added support for all operating systems, and all browsers.
Added descriptive comments for each function.
Fixes: #491
=> Fixes hotkeys for sending, replying to, and deleting messages.

js/mail.js
Fixes #297
Please review @zinks- @Xenopathic @irgendwie :)
=> set 'from' dropdown to current account, fix #297

lib/controller/accountscontroller.php, lib/service/accountservice.php, tests/controller/accountscontrollertest.php
``$this->params(..)`` is deprecated, so I removed all the calls and added method parameters
@DeepDiver1975 @LukasReschke @Xenopathic review please :)
=> remove deprecated params calls; add some unit tests

tests/controller/accountscontrollertest.php
=> some more accountscontroller tests

lib/controller/accountscontroller.php, lib/service/unifiedmailbox.php
=> Fix php errors accountscontroller etc

js/mail.js, templates/index.php
fixes #789 
@jancborchardt @aidanamavi @irgendwie review please
=> expand cc correctly

js/mail.js
Added checks to text area input on message bodies for both new messages and reply messages.
Added responses to programmatic input that resembles client input.
Fixes #582
=> Appropriately responds to programmatic input in message bodies.

.scrutinizer.yml
Ref https://scrutinizer-ci.com/g/owncloud/mail/inspections/322529f7-f4f8-4f6e-8c17-6e428b2c7452
@aidanamavi
=> Increase timeout

.travis.yml, appinfo/info.xml
Please review @DeepDiver1975 @ChristophWurst @aidanamavi
=> increase max-version to 8.2

lib/service/unifiedmailbox.php
@ChristophWurst @aidanamavi @irgendwie please review - THX
=> PHP variables start with a $ :wink:

lib/controller/messagescontroller.php, lib/message.php, lib/service/html.php, lib/service/htmlpurify/cidurischeme.php, lib/service/htmlpurify/transformurlscheme.php, tests/messagetest.php
=> Display inline images - fixes #138

lib/controller/accountscontroller.php, lib/service/unifiedaccount.php
@jancborchardt @ChristophWurst @aidanamavi please test - THX
=> Fix sending replies from unified inbox

js/mail.js
=> Properly convert html to text

lib/service/unifiedaccount.php
=> Keep unified inbox in sync

js/mail.js, js/views/message.js
partially implements #480 
IRC log:
> jancborchardt: christophwu: the only weird thing is that it still takes long switching folders (and accounts). Can’t we show the data from the cache?
@jancborchardt this PR should speed up switching folders ;-)
=> cache message lists (folders) in local storage

lib/controller/accountscontroller.php
@ChristophWurst @jancborchardt @irgendwie @clementhk please test THX
=> Save draft to the proper account in the unified inbox - fixes #845

css/mail.css
Fixes the extra left/right margin the reply composer got. Please review @ChristophWurst @irgendwie @zinks-
=> fix margin for reply composer to align with the message again

js/mail.js, js/views/message.js
does only work if the message was deleted via the mail app
@jancborchardt
=> remove message from cached message list

composer.json, composer.lock, lib/service/html.php, lib/service/htmlpurify/transformnoreferrer.php, tests/service/htmltest.php
=> Using kwi/urllinker for link detection

js/mail.js
@ChristophWurst @jancborchardt @Gomez 
#862
=> Apply receiver on composer open - fixes #862

css/mail.css
fix #804, check it @ChristophWurst
=> correctly ellipsize long account emails, fix #804

lib/account.php, lib/service/unifiedaccount.php
=> do not include recipient in reply CC list

js/mail.js
fixes #861
@jancborchardt @DeepDiver1975 review please
=> properly preserve any line breaks

js/views/folder.js
Fixes the double dash as mentioned in #803 – please check @ChristophWurst ;D
=> fix title double dash for unified inbox, ref #803

README.md
Moves the info from the wiki into readme plus adds info about Dovecot
=> Move wiki into Readme

css/mail.css
Fixes your mobile tappability issue @ChristophWurst :) Also review @zinks- @Gomez @Xenopathic 
(Also, you need to git add before git commit --amend, just tried it. ;)
=> increase clickability of star, add padding around

js/views/message.js
=> Fix search 

lib/service/unifiedaccount.php
fixes #878
@jancborchardt @DeepDiver1975 @irgendwie @LukasReschke please review :)
=> fix background checks for the unified inbox

js/mail.js, js/views/composer.js, templates/index.php
=> [WIP] Add forward functionality

js/mail.js
Fix #877, please review @DeepDiver1975 @irgendwie @ChristophWurst @LukasReschke @rullzer :)
=> only show one notification for unified inbox, fix #877

js/mail.js, js/settings.js
fixes #870 
@jancborchardt @DeepDiver1975 review please
=> clear message list and message cache after deleting accounts

js/views/composer.js
@jancborchardt  Please test and review and let me know what you think. :-)
Fix #921
=> Fix: New issue New mails sent from unified inbox #921

js/views/composer.js
=> Revert "Fix: New issue New mails sent from unified inbox #921"

css/mail.css
Please review @ChristophWurst @irgendwie @PoPoutdoor @itheiss
Fix #909
=> fix new account dialog not scrollable on mobile, fix #909

README.md
fixed Link to https://github.com/ChristophWurst which was incorrect and thus a 404 link see http://derecho.elijah.cs.cmu.edu:8585/owncloud
=> fixed 404 link in readme

templates/index.php
This makes use of the core styles which might come with pull request https://github.com/owncloud/core/pull/18506 to make the profile photos round.
What do you think @ChristophWurst @irgendwie @zinks- @Xenopathic?
=> round sender/receiver photos

js/mail.js, lib/controller/messagescontroller.php
@ChristophWurst 
Syntax is as follows:
GET 'http://localhost:8080/index.php/apps/mail/accounts/4/folders/SU5CT1g%3D/messages?ids=123,124'
=> Allow loading of multiple messages

css/mail.css
Looks less intense. @jancborchardt
=> Reduce opacity of trash and favourite icons

.jscsrc
=> jscs plugins removed

.jscsrc, js/autoredirect.js, js/background.js
@ChristophWurst Adjustment and first fixes
=> Jscs adjust

js/views/folders.js
Fixes #873 
@ChristophWurst @jancborchardt
=> Fix folder unread counter undefined bug.

css/mail.css
Your wish is my command @ChristophWurst
=> show pointer cursor when hovering message list as feedback

bower.json, templates/compose.php, templates/index.php
=> downgrade jquery autosize

bower.json
I assume this also has to be 0.3.0 ...
=> Adjust version to 0.3.0

js/ui.js
=> refactor ui.js to match revealing module pattern

js/search.js
=> refactor search.js to match revlealing module pattern

js/communication.js
=> refactor communication.js to match revlealing module pattern

js/cache.js
=> refactor cache.js

js/mail.js
=> make 'mail' a marionette application

js/ui.js
@Gomez @jancborchardt @enoch85 it's back ;-)
=> fix autocomplete

js/background.js, js/init.js, js/mail.js, js/models/account.js, js/ui.js, js/views/folder.js, js/views/message.js
=> use backbone/marionette triggers for UI events

js/background.js, js/cache.js, js/state.js, js/ui.js, js/views/composer.js, js/views/helper.js
=> use backbone collections/models for account data

README.md, composer.json, composer.lock, install_ubuntu.sh
Much faster and easier now.
@ChristophWurst Please try
@enoch85 Would be cool if you could test on new vm. Just follow the Readme.
=> Better dev setup

.travis.yml, Gruntfile.js, js/tests/TestSpec.js, js/tests/mocks/OC.js, js/tests/test-main.js, karma.conf.js, package.json
Tests don't pass, but the env is set up
=> add jasmine/karma for js unit testing

js/controller/accountcontroller.js, js/mail.js, js/models/accountcollection.js, js/service/accountservice.js, js/ui.js
=> use account service/controller in favor of SRP

js/controller/accountcontroller.js, js/init.js, js/mail.js, js/ui.js, js/views/app.js, js/views/settings.js
=> use marionette layoutview to manage regions

translation-extractor.php, translations.js
@Gomez @irgendwie @DeepDiver1975
=> add translation extractor script for js translations

js/controller/accountcontroller.js, js/controller/foldercontroller.js, js/mail.js, js/models/accountcollection.js, js/service/folderservice.js, js/ui.js
Still not perfect, but another piece of code that shouldn't live in ``ui.js`` is now split into controller/service components.
@Gomez @irgendwie review please ;-)
=> refactor folder loading to controller/service components

js/templates/message-list.html, js/views/messages.js
=> remove dots from buttons

js/templates/settings.html
fixes #1042
@irgendwie @jancborchardt @itheiss
=> fix escaping of settings mailvelope link

css/mail.css
Please review @ChristophWurst @Gomez @zinks- @colmoneill 
* remove background from New message button to make it compatible with upcoming 8.2
* reduce whitespace to unified inbox a bit
* adjust margin so New message and Check messages button are aligned to each other regarding height
* fix text alignment / size of Check messages button
=> fix buttons for New message and Check messages

README.md
@jancborchardt @Gomez please review this important change ;-)
=> Put @jakobsack to the active maintainers

.gitignore, Makefile, build.js, js/app.js, js/require_config.js, templates/index.php
basically this is groundwork for packaging the next release, see #981
@DeepDiver1975 @Gomez @irgendwie @jakobsack @jancborchardt  @zinks- 
With this PR we can optimize the packaged version of this app by putting all dependencies into a single file. This includes all the JavaScript and Template (HTML) files.
As running the optimizer is a task for packaging, I added the ``r.js`` call to our ``Makefile``. To separate between development and production environment, the only thing that came up my mind was the ``DEBUG`` setting of ownCloud. Therefore I use this variable to determine whether to include the optimized version or load any file asynchronously.
I still don't think that's the perfect, way… I'm sure someone will try to use the app with ``DEBUG`` set to true and no optimized file …
=> add requirejs optimizer for packaging

js/init.js, js/ui.js, lib/service/html.php, lib/service/htmlpurify/transformcssbackground.php, lib/service/htmlpurify/transformimagesrc.php
=> Block backgrounds from style attributes

README.md
I give up on how to rebase and squash the commits in https://github.com/owncloud/mail/pull/1066. This PR is exactly the same and already approved. So I´ll merge this and close the other.
Fixes #1061
=> Add info about nightly builds 2

js/app.js, js/init.js, js/ui.js, js/views/navigation-accounts.js, js/views/navigation.js, templates/index.php
no visual nor functional changes, just some cleanup for #1025 
@Gomez @irgendwie @jancborchardt @itheiss review please ;-)
=> use marionette view for rendering navigation

lib/service/htmlpurify/transformimagesrc.php
Fixes #1077 
@PoPoutdoor @ChristophWurst please review
=> Check if attr['style'] is set in TransformImageSrc

js/views/helper.js
This tiny commit fixes the hover tip of the address list.
@ChristophWurst @jancborchardt please review
=> Fix the generation of the address list

lib/service/html.php, lib/service/htmlpurify/transformhtmllinks.php
=> Add target="_blank" to all html links

css/mail.css, js/templates/composer.html
It was fun while it lasted, but finally fix https://github.com/owncloud/mail/issues/484 and the layout in general looking strange.
Please review @ChristophWurst @colmoneill @itheiss
=> fix position of send/reply buttons, fix #484

css/mail.css
Please review @irgendwie @ChristophWurst @Gomez @zinks-
=> fix unified inbox being under the new message button

lib/service/htmlpurify/transformimagesrc.php
=> Fix CSP issue for replaced tracking pixels

appinfo/application.php, lib/controller/proxycontroller.php, templates/redirect.php, tests/controller/proxycontrollertest.php
referrer and hostname are being injected now to make this class fully unit testable
@DeepDiver1975 @Gomez @irgendwie @jakobsack @itheiss @zinks- @Xenopathic @clementhk
=> make proxycontroller testable and add unit tests

package.json
=> increase grunt version to 0.4

lib/controller/folderscontroller.php, tests/controller/folderscontrollertest.php
@DeepDiver1975 @Gomez @irgendwie @jakobsack @itheiss @zinks-
=> add more folderscontroller unit tests

lib/controller/pagecontroller.php, tests/controller/pagecontrollertest.php
@DeepDiver1975 @Gomez @irgendwie @jakobsack @itheiss @zinks- @Xenopathic @clementhk
=> add unit tests for pagecontroller

lib/controller/messagescontroller.php, tests/controller/messagescontrollertest.php
the controller is still not fully covered. For 100% coverage we'd need some refactoring, e.g. 'show' is a PITA to write unit tests for…
@DeepDiver1975 @Gomez @irgendwie @jakobsack @itheiss @zinks- @Xenopathic @clementhk
=> add more messagescontroller unit tests

tests/service/accoutservicetest.php
Another class that didn't have any tests (https://scrutinizer-ci.com/g/owncloud/mail/code-structure/master?elementType=class&orderField=test_coverage&order=asc&changesExpanded=0)
=> add tests for accountsservice

.travis.yml
fixes #1105
@DeepDiver1975 @Gomez @itheiss @irgendwie @Xenopathic does anybody have any objections of running JS tests only once?
=> run CI js tests only once

lib/account.php, lib/controller/accountscontroller.php, lib/service/iaccount.php, lib/service/unifiedaccount.php, tests/controller/accountscontrollertest.php
@aspdye @Gomez @irgendwie @itheiss @jancborchardt  test and review this please :)
Next step: unit tests for ``Account``
=> refactor accountscontroller::draft to make it unit testable

.travis.yml
=> Remove all hhvm fragments

lib/account.php
@jancborchardt please test if that resolves the issue you noticed (https://github.com/owncloud/mail/pull/1093#issuecomment-147550190)
=> add missing use statement

lib/account.php, lib/controller/accountscontroller.php, lib/model/convertaddresses.php, lib/model/imapmessage.php, lib/model/imessage.php, lib/model/message.php, tests/model/imapmessagetest.php, tests/model/messagetest.php
still far away from good code quality, but at least works better than before… Maybe I'll have another look at this smelly code later on.
@jancborchardt does this fix your reported issue?
fixes #1111
=> improve mail address handling

lib/model/message.php
I forgot to remove it in #1126
=> remove debug error logging

README.md
This fix allowed me to install the dependencies properly on a Debian 8 machine.
=> Fix Debian/Ubuntu installation note in README.

js/views/helper.js
Toooo fast @ the ownCloud conf  :)
=> Fill to field - fixes #1134

js/templates/no-search-results-message-list.html, translations.js
@jancborchardt @Gomez @irgendwie @itheiss @aspdye easy to review ;-)
fixes #1135
=> fix no-search-result view rendering

js/views/setup.js
@itheiss @colmoneill @aspdye @jancborchardt @irgendwie test this please ;-)
fixes #911
=> don't show sidebar if account setup isn't successful

templates/redirect.php
Please review @LukasReschke @Gomez @ChristophWurst @irgendwie
=> improve wording of redirect warning

js/README.md
@DeepDiver1975 @jancborchardt @irgendwie @Gomez please have a look at this. Is this what was meant in #840?
partly fixes #840
=> js coding guidelines

css/mail.css, templates/redirect.php
Similar to https://github.com/owncloud/core/pull/20447, just use the h2 properly and fix the size so it’s like in core.
Please review @LukasReschke @owncloud/designers :)
=> use h2 for redirect warning and correct heading size

js/views/helper.js
fixes #1130 cc @ChristophWurst @irgendwie please review.
=> fix single quote escaping of to/cc fields

js/views/composer.js, lib/account.php
fixes #1172
@owncloud/mail I need some testers for this. IMAP drafts are complex and I can't test all the different setups. Simply switch to this branch and see if there are any errors in the browser console. Thanks ;-)
=> fix unified inbox drafts

appinfo/application.php, lib/controller/messagescontroller.php, tests/controller/messagescontrollertest.php
fixes #1197
@jancborchardt @owncloud/mail test & review please
=> remove deprecated mimetype method call

composer.json
=> bump min php version in composer.json to 5.4

appinfo/application.php
@ChristophWurst 
fixes #1207 for me
=> Use the proper method on the server object

CONTRIBUTING.md, README.md, issue_template.md
squashed version of #1214.
@owncloud/mail review & merge please
=> Aspdye issue template

templates/index.php
fixes #1201
Tested with oc7 and core master
@benjisympa @owncloud/mail test this review please
=> fix getSystemConfig error on oc7

appinfo/application.php, lib/controller/messagescontroller.php
fixes #1207
Tested with oc8, oc8.1, 8.2 and current master
oc7 could not be tested because of #1201
@owncloud/mail @PoPoutdoor @rullzer review please
=> Add version hack to support mimeTypeIcon on different core versions

js/views/navigation-accounts.js
Seems to do the trick.
Anyone wanna test and give feedback?
@ChristophWurst
fixes #618
=> Fixed #618

css/mail.css, css/mobile.css, js/controller/foldercontroller.js, js/templates/message-list-item.html, js/ui.js, js/views/app.js, js/views/helper.js, templates/index.php
=> CSS Coding Style #817

issue_template.md
- Move Mail app information to the top
- Add mail app version
=> Move most important issue information to the top

js/app.js, js/background.js, js/communication.js, js/controller/accountcontroller.js, js/controller/foldercontroller.js, js/init.js, js/models/message.js, js/search.js, js/service/accountservice.js, js/settings.js, js/state.js, js/ui.js, js/views/app.js, js/views/composer.js, js/views/helper.js, js/views/message.js, js/views/messages.js, js/views/navigation-accounts.js, js/views/settings-account.js
partially fixes #944
@owncloud/mail @ErikPel @Tagada85 I could not find any errors when using this branch. Please review/test this
=> decouple js modules

js/ui.js, js/views/message.js
introduced by #1258
@ErikPel @owncloud/mail easy to review
=> fix usage of modules

.travis.yml, README.md, appinfo/application.php, appinfo/info.xml, lib/controller/accountscontroller.php, lib/controller/folderscontroller.php, lib/controller/messagescontroller.php, lib/controller/pagecontroller.php, lib/service/autoconfig/autoconfig.php, lib/service/autoconfig/smtpserverdetector.php, lib/service/contactsintegration.php, tests/controller/messagescontrollertest.php
=> drop owncloud 7 support

.gitignore
This ignores NetBeans project directories
@owncloud/mail review + merge please :-)
=> ignore NetBeans project directory

lib/model/imapmessage.php, lib/service/html.php, lib/service/htmlpurify/transformurlscheme.php, tests/model/imapmessagetest.php, tests/service/htmltest.php
=> replace deprecated Util::getServerHost, Util::getServerProtocol

README.md
As discussed with @Gomez on IRC, I created a bountysource org for this app: https://www.bountysource.com/teams/owncloud-mail
=> Add bountysource badge

js/ui.js
Fixes https://github.com/owncloud/mail/issues/1295
@owncloud/mail Easy one.
=> Rename missed class - fixes #1295

CHANGELOG.md
Fixes:
https://github.com/owncloud/mail/issues/1282
@owncloud/mail
=> Add the first Changelog

css/mail.css, js/controller/accountcontroller.js, js/controller/foldercontroller.js, js/templates/messagecontent.html, js/ui.js, js/views/app.js, js/views/composer.js, js/views/message.js, js/views/messagecontent.js, js/views/messages.js, js/views/messagesitem.js, js/views/setup.js, templates/index.php
First step for #1306
TODO:
fixes #1273
=> Create MessageContentView, MessageView

README.md, bower.json, js/require_config.js, templates/index.php
:see_no_evil: https://www.versioneye.com/user/projects/567bd06ba7c90e003500033f :hear_no_evil: 
I did some testing and it seems that nothing broke.
The result can be seen here: https://www.versioneye.com/user/projects/56ce15e86b21e500355b10eb
=> update js libraries

js/views/setup.js
partially fixes #1311
@jancborchardt @ErikPel @Tagada85 easy to review
=> fill imap, smtp user and password inputs automatically

js/background.js, js/cache.js, js/communication.js, js/controller/accountcontroller.js, js/controller/foldercontroller.js, js/init.js, js/models/account.js, js/models/message.js, js/service/folderservice.js, js/state.js, js/ui.js, js/views/app.js, js/views/composer.js, js/views/folder.js, js/views/helper.js, js/views/messagecontent.js, js/views/messages.js, js/views/messagesitem.js, js/views/navigation-accounts.js, js/views/settings-account.js
partially fixes #1314 
fixes #1261
TODO:
=> Use account model instead of id

js/background.js, js/cache.js, js/communication.js, js/controller/foldercontroller.js, js/models/account.js, js/models/accountcollection.js, js/models/attachment.js, js/models/attachments.js, js/models/folder.js, js/models/foldercollection.js, js/models/message.js, js/models/messagecollection.js, js/models/messageflags.js, js/service/folderservice.js, js/state.js, js/ui.js, js/views/folder.js, js/views/messages.js, js/views/messagesitem.js, js/views/navigation-accounts.js
partially implements #1314 
@Gomez @owncloud/mail test and review please :-)
=> use folder model everywhere

.travis.yml
=> Adding build step to create appstore tar + use travis for deployment

appinfo/application.php, lib/controller/proxycontroller.php, tests/controller/proxycontrollertest.php
=> replace deprecated IHelper

lib/controller/messagescontroller.php, lib/service/contactsintegration.php
=> ignore raw images of the new dav app

.travis.yml, appinfo/register_command.php
Fixes the bug where occ failes resolving our service as we're asking the wrong container for it.
=> Fix service resolution

lib/service/unifiedaccount.php
fixes #1060
@owncloud/mail @jancborchardt
=> add missing color indicator of new messages

README.md
the 'owncloud-mail' org was deleted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/owncloud/mail/1367)
=> fix bountysource org

js/views/composer.js, js/views/message.js
that should make CI pass again
@owncloud/mail review please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/owncloud/mail/1370)
=> fix jscs errors

appinfo/app.php
The idea is to have the sorting start with: Files, Activity, Gallery, Mail, etc.
Please review @ChristophWurst @Gomez @DeepDiver1975
=> fix order in app navigation

js/app.js, js/controller/foldercontroller.js, js/init.js, js/templates/newmessage.html, js/ui.js, js/views/app.js, js/views/navigation.js, js/views/newmessage.js, templates/index.php
depends on changes in #1315
TODO:
partially implements #1306 
@owncloud/mail review please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/owncloud/mail/1321)
=> add NewMessage view

Makefile, composer.lock
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/owncloud/mail/1369)
=> update php libs, fix Makefile target 'update-composer'

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/owncloud/mail/1391)
=> update developer setup info

issue_template.md
It was a bit confusing when an issue started with a big »ownCloud Mail«. ;)
Please review @Gomez @ChristophWurst
=> fix confusing issue template headers

css/mail.css
Also related https://github.com/owncloud/core/pull/23702, please review @owncloud/designers
=> improve emptycontent style

CHANGELOG.md, js/views/composer.js, js/views/newmessage.js
fixes #1345, #1393
@jancborchardt @Gomez @pierreozoux review/test this please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/owncloud/mail/1394)
=> fix contacts autocompletion

README.md, issue_template.md, lib/account.php
I copied the if-clause form imap and changed it. After I try it I noticed it would be better to split the logs. So one for imap and one for smtp.
=> log SMTP communication #1392

css/mail.css
This fixes the new message textarea being way too small.
Please review @Gomez @ChristophWurst @owncloud/designers
=> fix min-height of new and reply textareas

lib/service/autoconfig/mozillaispdb.php
See also:
- https://github.com/owncloud/mail/commit/054e24f144e918696e05fe5be140d5e618865f74#diff-3040e49e696d53c05a7eab45dc26639dL301
- https://github.com/owncloud/mail/commit/054e24f144e918696e05fe5be140d5e618865f74#diff-699f1401ca0282b402393c2756f9e7e7R82
=> fix return statement of MozillaIspDb::query

.travis.yml
=> Removes autodeploy

tests/service/autoconfig/mozillaispdbtest.php
This test would have failed before #1405
@Gomez @Scheirle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/owncloud/mail/1406)
=> add simple testcase for MozillaIsbDb

js/app.js, js/controller/accountcontroller.js, js/controller/foldercontroller.js, js/controller/messagecontroller.js, js/ui.js, js/views/app.js, js/views/loadingview.js, js/views/messagecontent.js, js/views/messagesitem.js
=> Use LoadingView when loading messages

README.md, appinfo/info.xml
See https://github.com/owncloud/mail/graphs/contributors
=> Update contributors list

bower.json
See https://www.versioneye.com/user/projects/567bd06ba7c90e003500033f
=> Update backbone.radio, jQuery and requirejs

CONTRIBUTING.md
=> Update CONTRIBUTING text and remove contributor agreement link

js/app.js, js/communication.js, js/controller/foldercontroller.js, js/controller/messagecontroller.js, js/service/messageservice.js, js/views/messages.js
This adds an MessageService module, which is an abstraction of server communication like AccountService and FolderService.
Communication::get was not used anywhere, so I removed it.
@Gomez @irgendwie @skjnldsv @Scheirle @radlr
=> Add Messageservice

js/app.js, js/background.js, js/controller/accountcontroller.js, js/controller/foldercontroller.js, js/radio.js, js/routecontroller.js, js/router.js, js/templates/folder.html, js/templates/settings.html, js/views/folder.js, js/views/settings.js, lib/controller/pagecontroller.php, tests/controller/pagecontrollertest.php
=> Add Marionette AppRouter

js/controller/accountcontroller.js, js/controller/foldercontroller.js, js/views/messagecontent.js, js/views/messages.js
fixes #499
@Gomez @jancborchardt @skjnldsv review please
=> Load next messages automatically when reaching end of the list

js/views/helper.js
Since #1434 we have failing tests on master because @jancborchardt hit a PR with failing tests.
@jancborchardt @skjnldsv @Gomez @tahaalibra
=> Fix failing js code style tests

appinfo/application.php, lib/service/autoconfig/ispdb.php, tests/resources/autoconfig-freenet.xml, tests/service/autoconfig/ispdbtest.php
@Scheirle this is my attempt on testing xml based autoconfig automatically. What do you think? cc @Gomez @DeepDiver1975
=> test IspDb with real xml data

CHANGELOG.md
=> Update changelog to 043

bower.json, js/app.js, js/cache.js, lib/controller/pagecontroller.php, templates/index.php, tests/controller/pagecontrollertest.php
=> invalidate js cache if app version changes

CHANGELOG.md
I updated the changelog following advices on http://keepachangelog.com/.
We should add a changelog entry for EVERY feature/fix/whatever
=> update changelog for 0.4.4

CHANGELOG.md, js/views/app.js, templates/index.php
fixes #1384 and adds a loading spinner that is shown before Marionette has started and inserts its LoadingView
@jancborchardt @skjnldsv review please
=> bring back mobile menu toggle button

appinfo/database.xml
=> Narrow address column width to 255

CHANGELOG.md
=> add changelog entry for the address collector column width fix

.gitattributes, Makefile
=> Prevent merge conflicts of the changelog files

CHANGELOG.md
=> add 0.5.1 changelog

composer.json
=> change to secure connection

CHANGELOG.md, js/models/account.js, js/views/setup.js
=> Correct return for getFolderById - fixes #1514

composer.lock
=> Update composerlock to https urls

css/mail.css, js/templates/message-list.html, js/views/messages.js
A small UI enhancement, we don't need that button anymore.
@jancborchardt @skjnldsv check it out!
=> load more messages button is obsolete with infinite scroll

js/views/setup.js
this hides the message/folder content while loading the new account and shows a nice loading spinner instead.
=> smoother transition when adding another account

.travis.yml, appinfo/info.xml
@Gomez @DeepDiver1975 @jancborchardt @tahaalibra please review, this blocks other PRs (CI fails)
=> bump supported core version to 9.2

css/mail.css, css/mobile.css, js/controller/foldercontroller.js, js/templates/message-list.html, js/views/foldercontent.js, js/views/messagesview.js
=> remove 'Check messages' button and add scroll-to-refresh and shortcut

css/mail.css
@ChristophWurst as I showed you. Very very slight and barely noticeable, but a nice detail. ;)
=> introduce very slight gradient for message header to get rid of hard border

package.json
fixes CI, see https://github.com/owncloud/mail/pull/1581 for failing tests
@owncloud/mail
=> update Grunt dev dependency

js/views/messagesitem.js
fixes #783 
@jancborchardt @owncloud/mail
=> jump to next message faster when deleting the current one

js/views/messagesview.js
=> show only one spinner when loading the next page

js/controller/messagecontroller.js, js/state.js, js/views/foldercontent.js, js/views/messagesitem.js, js/views/messagesview.js
This simply saves the message object reference instead of only the ID. This will be helpful for the features are am planning to add soon.
=> Current message object ref

js/views/foldercontent.js
two more shortcuts of #160
@Gomez @jancborchardt @tahaalibra check it out
=> add shortcuts for 'flagged' and 'unseen'

templates/redirect.php
Please review @owncloud/mail :)
»Redirect warning« was a bit rash.
=> improve wording of link redirect

README.md, appinfo/info.xml
based on https://github.com/owncloud/mail/graphs/contributors
and https://github.com/owncloud/mail/graphs/contributors?from=2014-08-03&to=2016-08-02&type=c for the active ones
=> update active and past contributors in the readme

js/views/message.js
fixes https://github.com/owncloud/mail/issues/1586
@jancborchardt @owncloud/mail please test this thoroughly, I'm not too confident with all the unified inbox hacks spread across the code base…
=> fix unified inbox replies

js/service/messageservice.js
This fixes js errors when creating, but clearing a new message.
Steps to reproduce:
1. click 'New message'
2. type random content to the message content
3. wait 5sec
4. delete the content again
5. wait 5sec
6. see the js error
=> fix save-draft promise/callback

.travis.yml, appinfo/info.xml, js/app.js, js/templates/message-attachment.html, js/views/messageattachment.js, lib/controller/messagescontroller.php, lib/controller/pagecontroller.php, lib/controller/proxycontroller.php, lib/service/htmlpurify/transformurlscheme.php, templates/index.php, tests/bootstrap.php, tests/controller/messagescontrollertest.php, tests/controller/pagecontrollertest.php, tests/controller/proxycontrollertest.php, tests/service/loggertest.php
=> increase min core version to 9.0 and remove all version hacks

appinfo/application.php, templates/redirect.php
=> fix HTML link redirection

js/views/setup.js
if the setup was successful, we replace the setup view with a loading view.
fixes #1565
=> restore setup view state only on error

css/mail.css
All kinds of alignment issues before:
After:
Please review @ChristophWurst @Gomez @DeepDiver1975 @Henni @irgendwie :)
=> attachment style fixes

.travis.yml
Apparently the postgresql extensions were silently removed from Travis'es php 5.4 builds, hence I changed it to use php7. This should fix failing postgre builds
=> clean up travis file and fix PostgreSQL

js/app.js, js/background.js, js/controller/foldercontroller.js, js/views/navigation-accounts.js
fixes #751 and this js error on page load:
```
TypeError: account is null
cache.js:25:24
```
=> use simpler background fetcher and fetch incoming messages too

js/views/composer.js, js/views/foldercontent.js, js/views/helper.js, js/views/messagesitem.js
Finally get rid of all those errors :)
Please review @owncloud/mail
=> move from tipsy to tooltip
