owncloud/mail

- js/mail.js
As described [here](https://github.com/owncloud/mail/issues/427), 'New Messages' has some strange behavior on emtpy accounts:
- it is visible and active when the app loads
- it gets disabled when you click it
- when a user clicks on a folder again, the button does not become active again
fixes #427
> show 'New Message' button on emtpy accounts

- appinfo/application.php
- lib/controller/accountscontroller.php
looking at issue #330, I found out that the error message ```'Creating account failed: '``` was passed to translation with the exception message, resulting in an empty message string in the json response.
I also added some logging for further issues with autconfig.
> autoconfig logging added

- js/mail.js
- js/views/folder.js
- js/views/message.js
changeMessageFlags did not have the old attribute state anymore, so the evaluation logic was moved to the changeFlags listener function
With this change, the unread counter seems to work again. However, I'm sure there's possibly a better solution since I am no JavaScript expert ;-)
fixes #246
> decrease unread counter

- js/mail.js
This PR fixes #463: the 'New message' button is reset to enabled when clicking on an a message
Additionally, the loading is also shown when switching from 'New message' to an existing one.
> set 'New Message' button enabled; show loading animation

- js/views/message.js
Currently we show a little loading spinner while the message is being starred. This results in perceived slowness of the app.
So instead, we just lie and change the status directly. In the off-case there is an error it will just change back.
Please review @DeepDiver1975 @wurstchristoph @Gomez @zinks- @LukasReschke
> directly change star state in the interface for quick feedback

- lib/message.php
Attachments like signature.asc and smime.p7s will just not be shown in the attachment list. Fix #126
Also if that attachment was the only one, the attachment indicator will not show either.
Please review @DeepDiver1975 @wurstchristoph – there’s probably a more elegant way of defining which files to skip instead of hardcoding them twice. ;)
Also, do you know of any other technical files which show up as attachments which should be hdiden? cc @Gomez @zinks-
> hide technical attachments like signature.asc and smime.p7s, fix #126

- js/mail.js
rendering the new-message-view requires ```Mail.State.accounts``` variable, which is empty if no accounts have been added yet.
loading it using an ajax request fixes #469
> reload account data after adding another account

- css/mail.css
Instead of 35% (message list) and 65% (message detail view) width, it’s now 30% and 70%. This gives more space to the actual emails.
Please review @DeepDiver1975 @wurstchristoph
> reduce message list width in favor of message detail view

- js/views/sendmail.js
Before we didn’t clear them visually like we did with the other fields. Please review @DeepDiver1975 @wurstchristoph
> empty cc and bcc fields on send as well

- js/mail.js
- templates/index.php
Fix #99
Please review @RandolfCarter @seal20 – btw you’re also welcome in our IRC channel #owncloud-mail on freenode. :)
cc @DeepDiver1975 @wurstchristoph @zinks-
> disable send/reply buttons unless recipient and either subject or message body is filled

- lib/controller/accountscontroller.php
Changing from the strange-looking capitalized »RE:« prefix to the more commonly used (and less screamy/technical ;) »Re:«.
Please review @DeepDiver1975 @wurstchristoph @zinks-
> use correct capitalization for 'Re:' prefix, prevent stacking

- js/mail.js
- templates/index.php
It’s useful in the Files app because there files with different dates are directly among each other.
Mails however are always sorted by date so shading the date is not useful here. Removing it also fixes the visibility issues, fix #201
> Remove shading of date

- js/mail.js
(Manual rebase of https://github.com/owncloud/mail/pull/333)
This moves the manual setup toggle code into a function. Also fixes #331 in that the manual setup area is only closed on successful connection.
Please test @Xenopathic @zinks- @PoPoutdoor @wurstchristoph
> if manual setup is open, close it after successful connection, fix #331

- composer.json
- composer.lock
I made the syntax of composer.json a little less crazy, and fixed some whitespace errors. Big change is a composer.lock update. Also, Horde_Imap_Client now requires version 2.27.0 and above, to fix the quote filter issue.
Fixes #444, #468 
cc @DeepDiver1975 @jancborchardt @wurstchristoph @clementhk @marlemion @MorrisJobke
> Update composer.lock, require Horde Imap Client >=2.27.0

- js/mail.js
Fixing https://scrutinizer-ci.com/g/owncloud/mail/issues/master/files/js/mail.js?selectedAuthors%5B0%5D=hey%40jancborchardt.net&orderField=path&order=asc
Apparently the + should be last on the line, not first on the next.
> fix Scrutinizer line break issues

- js/mail.js
- lib/account.php
- templates/index.php
Three small changes here:
- SMTP default port has been changed to 587, which is the SMTP submission port, and is more suitable than port 25 which is the MTA port.
- Security mode dropdown uses nicer labels: `None`, `SSL/TLS` and `STARTTLS`, like how Mozilla Thunderbird does it.
- I also noticed that for no security, one must pass `false` into the Horde libraries, not `none` as we are at the moment. The third commit fixes that (and implements support for adding custom security modes in the future).
Request to be merged for 0.1 @jancborchardt ?
> Security mode fixes and improvements

- lib/account.php
Array to string conversion error in log. We log message IDs in other places too, so this makes sense. I added the mailbox ID so the admin has some idea of the context.
> Fix logging of message ID on move to trash

- css/mail.css
- css/mobile.css
The date was barely readable anyway because of overlap with the sender. So for now we don’t show it on narrow / mobile screens at all so that at least the sender is readable.
Please review @Xenopathic @zinks- @PoPoutdoor @tomneedham
> fix layout of message list on narrower screens and mobile, do not show date for now

- css/mail.css
Positioning the star left of the title instead of on the user avatar makes it clearer that it will star the message instead of the contact.
Fix https://github.com/owncloud/mail/issues/570, please review @colmoneill @Gomez @wurstchristoph @zinks- :)
> reposition message indicators, especially star, fix #570

- tests/imap/abstracttest.php
It's annoying to see a PR marked as failed because the (encrypted) credentials sent to Travis aren't available for forks. Tests are marked as skipped instead of throwing an exception in this case. It's similar to not having the required extensions for memcache tests, as a comparison.
This PR is coming from my fork to test it.
> Skip IMAP tests if credentials are unavailable

- templates/index.php
fix #566 
Please review @colmoneill @blizzz @Xenopathic @wurstchristoph @irgendwie 
@blizzz thank you for the code! :) As you see you can improve yours by using the standard `.hidden-visually` class from core, as well as adding `tabindex="-1"` so it doesn’t interfere with keyboard navigation.
> fix account form being autofilled with username and password in Chrome & Safari

- js/send-mail.js
- js/views/sendmail.js
fix #606. The notification vanishing when in the background is a core issue, see https://github.com/owncloud/core/issues/16121
Please review @DeepDiver1975 @wurstchristoph @Xenopathic @irgendwie 
To test:
1. Load mail app
2. Compose reply or new message
3. Deactivate your wifi
4. Press »send« or »reply«
5. See the error and see the buttons being active again
> on failed connection activate send/reply button again

- lib/controller/messagescontroller.php
- templates/index.php
This makes the redirect in Firefox work again by using CSP instead of a sandboxed iframe. Unit tests are coming later because the message controller has some hard-coded references to other classes with side-effect such as `\OCA\Mail\Account`. Trying to come up with a fix for that as well in another PR.
Requires https://github.com/owncloud/core/pull/16463 for optimal security. Should work without though.
Fixes https://github.com/owncloud/mail/issues/206
cc @DeepDiver1975 @jancborchardt
> Make redirect in Firefox work again and harden CSP policy

- lib/account.php
- lib/searchmailbox.php
Fixes #690 , replaces #692 
The only issue I can see here if if the parent mailbox already has a special use IMAP attribute set, then would end up with two.
> Fixed the way the Flagged mailbox gets its display name

- css/mail.css
Fixed white space rendering for the message list within the Gecko web browser engine.
Fixes: #712 
Please review @wurstchristoph @jancborchardt @colmoneill
> Fixed white spacing rendering.

- lib/searchmailbox.php
Amended previous changes I made to SearchMailbox::getStatus() that fixed a scrutinizer issue the wrong way
ref https://github.com/owncloud/mail/pull/694#issuecomment-104562731
@jancborchardt @DeepDiver1975 check it out
> Fix SearchMailbox::getStatus()

- css/mail.css
- templates/index.php
fixes #726 
Now it looks like this:
@jancborchardt is there a way to show the full text when hovering?
> show ellipsis on long mail addresses

- css/mail.css
- templates/index.php
Tiny tiny change, as pointed out in #567; centring the new email form to the middle of the viewport.
Given the 'absolute positioning' nature of this app, I'm centring to the middle of the browser, not the middle of the left pannel. The difference being that on first launch of the Mail app in oC, you get this form prompt with no left menu, as the screenshot in #567 shows.
> centering the "add new email address" form

- lib/controller/messagescontroller.php
without this change, the application returns HTTP 500 and an error page
("This email (808) can't be found. Probably it was deleted from the server recently. Please reload.")
> return HTTP 404 if message does not exist

- css/mail.css
Previously when you had a large reply box and scrolled down, the reply input boxes would overlay the fixed header bar. This fixes that.
Please review @aidanamavi @colmoneill @irgendwie :)
> fix reply fields overlapping message header bar

- js/mail.js
The background message fetcher didn't stop fetching messages of the previous
folder when the folder was changed. This caused 404s because the message
IDs and folder IDs did not match
> resolved message fetcher timing issues

- appinfo/application.php
- css/mail.css
- js/mail.js
- js/views/sendmail.js
- lib/account.php
- lib/controller/accountscontroller.php
- lib/controller/folderscontroller.php
- lib/controller/messagescontroller.php
- lib/mailbox.php
- lib/message.php
- lib/service/accountservice.php
- lib/service/iaccount.php
- lib/service/imailbox.php
- lib/service/unifiedaccount.php
- lib/service/unifiedmailbox.php
- templates/index.php
> Unified Inbox

- js/mail.js
Hello
Firefox e10s crash when it goes throught the registerProtocolHandler function.
The only workaround I found is a try catch around this function.
It's shows this if the fix isn't applied :
Here is the complete error : 
```
NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "aWindow.QueryInterface is not a function" {file: "resource://gre/modules/PrivateBrowsingUtils.jsm" line: 49}]'[JavaScript Error: "aWindow.QueryInterface is not a function" {file: "resource://gre/modules/PrivateBrowsingUtils.jsm" line: 49}]' when calling method: [nsIWebContentHandlerRegistrar::registerProtocolHandler]
```
Thank you.
> Prevent Firefox e10s to crash when registerProtocolHandler

- lib/controller/messagescontroller.php
We now rely on CSP instead of sandboxed iframes. Partially addresses #767
> Remove CSRF token

- lib/controller/accountscontroller.php
@DeepDiver1975 @Nawuko please review
fixes #813 and replaces #814 
Additionally to ``$autoDetect``, also integer parameters like ``$imapPort`` are currently not being casted. This should be fixed with this PR
> fix PHPDoc parameter types for proper casting to bool/int

- lib/service/unifiedmailbox.php
@DeepDiver1975 @aidanamavi @Xenopathic review please
partially fixes #803
> unified inbox: respect 'count' parameter and return only the first 'count' messages

- lib/controller/messagescontroller.php
- tests/controller/messagescontrollertest.php
partially fixes #799
Firefox seems to ignore it for some reason, but Chrome caches message bodies as expected.
@LukasReschke @DeepDiver1975 @Xenopathic review please
> enable HTTP caching for HTML message bodies

- js/mail.js
- js/views/helper.js
Fix https://github.com/owncloud/mail/issues/328, the base is taken from how we did it in files but we only need a simple part of it: https://github.com/owncloud/core/pull/15260 – it uses the getScrollbarWidth function defined in core js.js already.
> adjust header bar width, fix #328

- js/mail.js
- js/views/message.js
@jancborchardt please test if this fixes the caching errors you noticed (messages still being shown after they have been deleted)
> replace message list cache on reload

- js/views/helper.js
fixes #915
@rakshazi please check if this fixes the issue you reported
> duplicate core js.js getScrollBarWidth for older oc releases

- js/views/composer.js
Fixes #921 
Here is my second attempt to fix this nasty dirty little thing. It feels dirty, drove me nuts and made me crying. I had to dig deeper than I wanted and to be honest I did't understand most of the things I saw :-)
To make replying from the unified inbox work I had to do some digging in the available objects to get the account id. When replying from the unified inbox I had to exclude ***options.messageId*** and ***options.folderId*** otherwise an Exception was thrown: ***Horde_Imap_Client_Exception, Message: Could not open mailbox "all-inboxes", Code:200***.
I'am not really satisfied with this approach but I don't know better as the whole thing is currently a miracle for me.
I think i've tested every posible combination and everything worked for me.
Please review carefully …
> Fix: New mails sent from unified inbox

- js/mail.js
This ensures messages are shown immediately when either clicking on a notification (which triggers a folder refresh and cached messages are shown first) or if you are in a folder other than the inbox with new messages and switch to the inbox (same reloading/caching issue).
possibly fixes issues reported in #919
@jancborchardt @irgendwie
> cache new messages loaded in background

- js/mail.js
I guess this issue was introduced with my PR #937. The problem was that messages (message bodies to be precise) that haven't been cached yet aren't removed from the cached folder message list. It's a scenario I didn't think of when writing this ``removeMessage`` function :see_no_evil: 
fixes #954
@jancborchardt @DeepDiver1975 test this please :)
> remove new uncached messages from folder list cache

- templates/compose.php
For some mysterious reason, the mailto composer seems to use underscore to render the template while in contrast the standard composer uses Handlebars… :confused: 
This isn't necessarily a permanent fix, but I don't know how to resolve this now.
fixes #844
> change attachment template to underscore template

- js/views/message.js
fixes #952 
If anybody has an idea why the message has no 'from' attribute, let me know ;-)
@jancborchardt please test if it's fixed now :-)
> don't show a placeholder if 'from' isn't set on the message

- js/mail.js
- js/views/composer.js
- lib/controller/messagescontroller.php
Yet another hack to get unified inbox working ;-)
__IMPORTANT:__ clear your local storage with ``localstorage.clear()``. Otherwise you'll run into client side errors when trying to reply to a message that has been cached before. (``accountId`` and ``folderId`` aren't set on old messages).
fixes #949
@jancborchardt @DeepDiver1975 @irgendwie @PoPoutdoor
> set accountId and folderId on each message to fix unified inbox replies

- js/views/message.js
Due to my little mistake in PR #957, no avatars are shown now. This PR brings them back again.
@jancborchardt @Gomez @irgendwie @itheiss easy to review ;-)
> show sender avatar again.

- js/views/composer.js
- js/views/message.js
As we moved from tipsy to tooltip (https://github.com/owncloud/core/pull/17075), I changed them for the mail app.
This resolves some issues / problems we had, like the recently https://github.com/owncloud/mail/issues/929, but also creates new problems:
Please review this and search for bugs! :+1:
> Replace tipsy with tooltip

- js/init.js
Fixes #912
It's done by checking if the message list is visible or not. Good idea? Bad idea? Review pls! @ChristophWurst
> Fix message deletion by 'del' hotkey while adding a new mail account.

- package.json
fixes warning when executing ``npm install``.
Previously it said:
``npm WARN package.json mail@0.0.1 license should be a valid SPDX license expression``
@Gomez @jancborchardt @itheiss
> update version, fix license

- tests/bootstrap.php
Most apps can't run their tests any more because of a new restriction in core:
https://github.com/owncloud/core/pull/18396
This fixes the bootstrap.
@DeepDiver1975 @jancborchardt
> Add tests to the list of allowed paths

- bower.json
- js/tests/test-main.js
- karma.conf.js
I found out oc7 and oc8 have different js vendor paths, therefore jQuery could not be loaded properly in oc7 karma tests.
Switching to an own jQuery version (``js/vendor/jquery/dist/jquery.js``) fixes the problem for now.
If I didn't miss anything, we should have green travis status again :speak_no_evil: 
@Gomez @irgendwie @jancborchardt
> use own jquery for unit tests because oc7/oc8 path differs

- tests/bootstrap.php
this is needed in addition to #1023 because of new path restrictions of core (https://github.com/owncloud/core/pull/18839)
@Gomez @irgendwie @Xenopathic @nickvergessen @oparoz
> load app in bootstrap.php to fix php unit tests

- Makefile
- package.json
The Makefile installs now only js deps for production use (bower for frontside & requirejs for the optimization).
A makefile option for dev deps can now be done too.
> Only install production js deps

- js/ui.js
Previously the opacity was stacked, and hence quotes on multiple levels would become unreadable. This just makes all the quotes grey.
Please review @DeepDiver1975 @enoch85 @zinks-
> use grey instead of transparency for quoted mails so they don't get unreadable

- css/mail.css
The tooltips for the names in the mail header are now normal, not transparent anymore. Please review @irgendwie and everyone. :)
> fix transparency of tooltip in mail header

- tests/applicationtest.php
It's more or less useless, but at least code coverage should be pushed if the application is constructed when testing :D
https://scrutinizer-ci.com/g/owncloud/mail/code-structure/master?elementType=class&orderField=test_coverage&order=asc&changesExpanded=0
> construct application to increase code coverage

- tests/service/contactsintegrationtest.php
ContactsIntegration didn't have any tests: https://scrutinizer-ci.com/g/owncloud/mail/code-structure/master?elementType=class&orderField=test_coverage&order=asc&changesExpanded=0
@itheiss @colmoneill should be easy to review ;-)
> add tests for contactsintegration

- .scrutinizer.yml
@DeepDiver1975 @Gomez @irgendwie good idea? Today travis is again extremely slow, therefore all scrutinizer checks fail :/
> increase timeout to prevent failing checks when travis takes too long

- .travis.yml
Directory | Size
---|---
node_modules | 163MB
js/vendor | 3.2MB
vendor | 12 MB
| without cache | with cache
---|---|---
composer | 17.85s | 3.29s
npm | 67.09s | 40.50s
bower | 6.22s | 2.84s
I made this comparison by clearing the cache and running the test twice.
Result: we can save about 45s per build, that's 7.5min for running all 10 tests :rocket: 
@DeepDiver1975 @Gomez @Xenopathic @clementhk @zinks- review please
> enable dependency caching for travis to speed up CI builds

- lib/account.php
- lib/controller/accountscontroller.php
- lib/mailbox.php
- lib/model/imapmessage.php
- lib/model/imessage.php
- lib/model/message.php
- lib/model/replymessage.php
- lib/service/iaccount.php
- lib/service/unifiedaccount.php
- tests/controller/accountscontrollertest.php
- tests/controller/messagescontrollertest.php
- tests/model/imapmessagetest.php
- tests/model/messagetest.php
- tests/model/replymessagetest.php
Since this is one of our most critical methods (used to send and reply messages), we should unit test this as much as possible to prevent issues like #1091.
I split the method into more testable chunks. Now the controller creates a new ``Message`` object (or ``ReplyMessage`` when replying) and passes it to the account, which handles the rest.
* Unit tests
There's further potential to improve new message and reply handling, but I'll try to keep this PR as small as possible and do everything step-by-step.
> split accountscontroller::send into testable chunks and add tests

- js/init.js
If you are in the searchbar and hit the 'del'-key, the current focused message gets deleted. With this commit if the searchbar is focused, messages won't get deleted.
**Also** re-adds the exception for the 'add mail account' dialog (#969), which accidentally got deleted in this commit:
https://github.com/owncloud/mail/commit/d7315a8522d574cdb728fcc18ae6453504b901ce#diff-e3f4efbe9f975868bcbac1c372abecf8L210
> Fix message deletion hotkey if searchbar is focused.

- Gruntfile.js
Lets ignore the mail.min.js, confuse if you run grunt locally
@ChristophWurst Easy merge. No effect if its missing
> Ignore mail.min.js in jscs jshint check

- js/search.js
- js/searchproxy.js
- js/ui.js
- templates/index.php
I added a search proxy that is registered as app search on page load. The actual search module is then registered to that proxy shortly afterwards when it has been loaded asynchronously.
The only disadvantage of that approach is that the search field actually doesn't work for the time it needs to load the search module. However, that's actually a very short time on a production system since JavaScript source files are combined and compressed. Hence, search is not working for less than a second.
@jancborchardt @irgendwie @Gomez review please
fixes #1057
> fix search by adding a proxy

- lib/account.php
The constructor of "Horde_Imap_Client_Mailbox" requires a "false" for UTF-8 encoding. In the current code-base a "true" was set so that the horde-backend uses UTF-7 which caused problems with translated draft-folders (like "Entwürfe" which where mistransformed to "Entw??rfe").
> Fixed UTF7 encoding instead of UTF8 for mailbox-draftfolders

- lib/controller/messagescontroller.php
As described in issue #1128, the unified inbox hack I introduced in PR #956 was not implemented for bulk message loads. Now we have a unified-unified-inbox hack :see_no_evil:
@owncloud/mail give it a test please. I'm not sure if that works in all scenarios.
@Gomez thanks for the hint of the missing accountId
fixes #1128
> fix unified inbox replying

- appinfo/application.php
- js/controller/foldercontroller.js
- lib/controller/pagecontroller.php
- tests/controller/pagecontrollertest.php
This brings back mailto link support. Works with recipient, cc, bcc, subject and body.
@owncloud/mail review please
fixes #1020
> fix mailto composer

- lib/mailbox.php
Yahoo! mail use "Bulk mail" as junk/span and until now is considered a common folder.
> Add 'bulk mail' as junk/span special folder.

- lib/account.php
- lib/controller/messagescontroller.php
- lib/service/accountservice.php
- lib/service/unifiedaccount.php
Since unified inbox felt kind of slow when initially loading the app after browser cache has been cleared, I had a look at what might cause it. It turned out the uniform inbox implementation re-creates accounts again for each message that is being loaded (bulk message load route). This resulted in 32 imap connections for 2 imap accounts. Moreover, whenever the special folder 'inbox' was queried, the imap server was asked for a list of mailboxes.
I added some in-memory caching to prevent useless calls to the imap server per request. As a result, loading 10 messages of the unified inbox in bulk now takes about 3.9s, where it took 12.8 without those optimizations. 3 instead of 32 imap connections are needed.
@owncloud/mail please test and review this, thanks.
> Speed up unified inbox loading by caching some redundant imap calls

- js/init.js
- js/views/app.js
This moves global selectors into the app-view, because it feels less hacky to me then. I also added some TODOs, where a bigger refactoring is needed.
Some day I would like to fully get rid of hacky files like init.js and ui.js. We should try to encapsulate all view code into view classes instead of global event handlers that nobody really remembers what they are doing :smile: 
@owncloud/mail have a look please. The easiest is to review each of the commits since I tried to do it step-by-step.
> Fewer global selectors

- Makefile
This resolves the issues of unnecessarily installing composer dependencies when trying to optimize javascript files.
@owncloud/mail review please
This target is executed either directly or when packaging the app for the appstore, where dependencies are installed anyway.
> remove cyclic dependency from Makefile

- bower.json
updates backbone from 1.1.2 to 1.2.3
and marionette from 2.4.2 to 2.4.4
> update backbone, backbone.marionette

- appinfo/register_command.php
- lib/command/createaccount.php
- tests/command/createaccounttest.php
This adds a simple command as described in #1125.
implements #1125 
TODO:
@DeepDiver1975 @hitam4450 @owncloud/mail
> add console command for account creation

- templates/error.php
- templates/redirect.php
I saw those erros on travis:
```
PHP Parse error:  syntax error, unexpected '<' in ./templates/error.php on line 22
Parse error: syntax error, unexpected '<' in ./templates/error.php on line 22
Errors parsing ./templates/error.php
No syntax errors detected in ./templates/index.php
PHP Parse error:  syntax error, unexpected '<' in ./templates/redirect.php on line 23
Parse error: syntax error, unexpected '<' in ./templates/redirect.php on line 23
Errors parsing ./templates/redirect.php
```
this was caused by PR #1277
@owncloud/mail @ErikPel easy to review
> fix templates

- .travis.yml
- Makefile
- tests/imap/abstracttest.php
fixes #1291
- Uses trusty beta instead of docker based infrastructure
- it is needed for running docker images
- MySQL has to be installed explicitly as it's not yet included
- Makefile is used for starting/managing the imap docker
- This can be used locally by all developers
- **phpunit now needs 2-3 seconds instead of 70** as the IMAP server is run locally and xdebug is disabled if not needed
Before (last master build):
After (this PR):
Summing up, it's 34:40 vs. 13:42. However, that's not all – the docker based version can also be run concurrently! 
@owncloud/mail have a look at this :rocket:
> Add imap docker for faster CI builds

- css/mail.css
Please review @owncloud/mail, fix #1241
> reduce width of account indicator bar from 5 to 2px

- composer.json
Fixes the following composer error:
>   Installing pear-pear.horde.org/horde_translation (2.2.1)
>
>    Downloading: Connecting...    Downloading: Connecting...    Downloading: Connecting...
>
>                                                                               
>
>  [Composer\Downloader\TransportException]                                     
>
>  Your configuration does not allow connection to http://pear.horde.org. See   
>
>  https://getcomposer.org/doc/06-config.md#secure-http for details.            
https://travis-ci.org/owncloud/mail/jobs/111795408, https://github.com/owncloud/mail/pull/1324
@jancborchardt @owncloud/mail review please
> Allow composer to use http

- css/mobile.css
I found myself frequently missing the date of the mail when on mobile. There’s no real reason to hide it as usually there’s plenty of space right to the sender. So the elements are now just like on the desktop.
Please review @owncloud/designers @owncloud/mail
> don't hide date on mobile, list view exactly as on desktop

- js/templates/composer.html
- js/views/attachments.js
- js/views/composer.js
- js/views/message.js
- js/views/messagecontent.js
Replacing Backbone views with Marionette views reduces code complexity and fixes the attachments bug.
fixes #1371 
@jancborchardt @owncloud/mail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/owncloud/mail/1378)
> Fix attachments

- CHANGELOG.md
- js/templates/folder.html
- js/views/folder.js
- js/views/messagesitem.js
- js/views/navigation-accounts.js
this solves issue #540 
Currently the drafts shows unseen/unread count. this solution would enable to show total count for the drafts folder only.
review @Gomez @ChristophWurst, This is my first PR, i am open for code review
> show total count for drafts folder

- lib/service/autoconfig/autoconfig.php
- lib/service/autoconfig/ispdb.php
- lib/service/autoconfig/mozillaispdb.php
- tests/service/autoconfig/ispdbtest.php
Before this PR we only query `https://autoconfig.thunderbird.net/v1.1/{DOMAIN}`. A lot of small providers are not in this source.
This PR adds provider specific source(s): `https://autoconfig.{DOMAIN}/mail/config-v1.1.xml`, ...
Related:
- https://github.com/owncloud/mail/issues/678
- https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration
> Improves autoconfig by querying different mozilla isp sources

- js/app.js
- js/controller/accountcontroller.js
- js/controller/foldercontroller.js
- js/ui.js
This PR moves some code to better fitting places. Moving the start-up logic out of classes it doesn't really fit will make the introduction of the Backbone router easier as we now have all in one place.
I couldn't find any new errors, @Gomez @jancborchardt test this please
> Move startup logic to App::onStart

- js/views/helper.js
All in the title! 
If the core color generator offers the `string.toHsl()` function, then we're using it for the accounts colors! :)
refs owncloud/core#23768
fix #1423
> Use core color generator if available

- js/views/helper.js
Divide the hue value by 20, round it and multiply it again by 20.
This allows for (360/20) 18 differents colors.
@jancborchardt 
Fix #1428
> Force visually distinguishable account colors

- appinfo/database.xml
- lib/controller/accountscontroller.php
- tests/controller/accountscontrollertest.php
> Increase Address column width to 256

- lib/controller/accountscontroller.php
- lib/service/logger.php
As this interface has now changed the second time, I changed our Logger to not explicitly implement that interface anymore. In fact, it's even impossible to implement because in 8.2 the method signature has the Exception typehint, which has been removed in 9.1 and PHP does not allow method overloads.
@DeepDiver1975 should this be considered when interfaces in core are changed?
@Gomez @Scheirle
> Make Logger independent of ILogger

- lib/service/autoconfig/ispdb.php
Fixes #1417
How many seconds should we wait before we abort? (currently 3)
> Adds a timeout to the ispdb autoconfig query.

- js/views/composer.js
fixes #1440
This was caused by the new app router, it reacted to the url change and navigated away.
@jancborchardt @tahaalibra @skjnldsv @irgendwie super easy to review :D
> Prevent the browser from navigating on cc/bcc click

- css/mail.css
- js/templates/account.html
- js/views/account.js
fixes #677
Suggestions on what folders are to be considered important und should be shown even when the account is collapsed are welcome.
We can think about automatically hiding drafts if there are none, but as long as the client-side is not always up to date with the server state I'd like to not add that enhancement yet and wait until we have solved that cleanly.
@jancborchardt I'm afraid this is very badly discoverable. Any idea how to solve that?
> Make accounts collapsable and show only important folders

- js/controller/accountcontroller.js
fixes #1458
My bad, I forgot to resolve the promise when no accounts are configured, which led to the backbone router not being started. Small bug with great impact.
@Gomez @jancborchardt @irgendwie @DeepDiver1975
@Scheirle @kajla please check if that fixes the reported issue for you
Note to myself: Test releases before releasing…
> Resolve accounts loading promise in all cases

- Makefile
There is no reason to include those in the archive.
@tahaalibra please review
> don't include js tests when packaging

- js/service/messageservice.js
- js/views/composer.js
fixes #1450
@jancborchardt  please review
> return UID correctly so old drafts are automatically removed

- css/mail.css
- js/app.js
- js/controller/messagecontroller.js
- js/models/attachment.js
- js/service/attachmentservice.js
- js/templates/message-attachment.html
- js/templates/message-attachments.html
- js/templates/message.html
- js/views/app.js
- js/views/message.js
- js/views/messageattachment.js
- js/views/messageattachments.js
- lib/controller/messagescontroller.php
- lib/model/imapmessage.php
This moves attachment rendering out of the message view and shows attachment as blocks instead of a simple list:
My goal is to make the attachments view ready for enhanced attachment actions, like integration with other apps (contacts, calendar, maps) and previews of other file types (ref #1374, #79).
TODO:
Ideas for future PRs:
- use popover for download and other attachment actions
fixes #1308
> Show attachments as blocks instead of list to allow enhanced actions

- css/mail.css
- templates/index.php
Fix some misused css data and reorder the sidebar layout to have a full width new message button without the need of js.
refs #1463
@ChristophWurst
> Fix button and sidebar layout

- js/require_config.js
Those are left-overs from the first use of requirejs in this app. Apparently this was never really used, so we can savely remove it.
@tahaalibra please review
> remove unused require shims

- js/tests/test-main.js
Following #1465, also removing left-over shims of requirejs from the tests.
> remove unused require shims from tests

- CHANGELOG.md
- js/service/messageservice.js
- lib/account.php
Finally, this pesky bug is fixed. I really feel stupid now thinkig about how many hours it took me to discover this tiny little flag ``@param boolean $flowed  Send message in flowed text format.``. For some reason I overlooked that in previous debugging sessions… :disappointed: 
@jancborchardt @Gomez @tahaalibra @Scheirle @nicokaiser please test
fixes #1151
> Dont break lines

- CHANGELOG.md
- README.md
- bower.json
- css/mail.css
- js/app.js
- js/models/dav/calendar.js
- js/radio.js
- js/require_config.js
- js/service/attachmentservice.js
- js/service/davservice.js
- js/templates/calendar.html
- js/templates/message-attachment.html
- js/views/app.js
- js/views/calendarspopoverview.js
- js/views/calendarview.js
- js/views/messageattachment.js
- lib/controller/messagescontroller.php
- lib/controller/pagecontroller.php
- templates/index.php
- tests/controller/pagecontrollertest.php
fixes: https://github.com/owncloud/mail/issues/79
TODO:
BUGS:
FUTURE IDEAS
- Show a preview of the calendar data
> add ability to import ics attachments into the calendar

- CHANGELOG.md
- js/routecontroller.js
if the folder id is not found then the user will be sent to the first folder of that account
please review @ChristophWurst
> show first folder of an account incase of invalid folder id

- js/models/account.js
- js/routecontroller.js
- js/views/composer.js
The folder data structure is a tree, hence we need to traverse down all hierarchies when doing a search by id.
Note: one could optimize the algorithm by decoding the folder id and guessing the path. I'll leave that for the Mail 10.0 release :hear_no_evil: 
fixes https://github.com/owncloud/mail/issues/1503
@tahaalibra @Gomez @DeepDiver1975 @clementhk @Scheirle review please
> traverse folders correctly when searching by folder id

- CHANGELOG.md
- js/views/account.js
Fix: the popover should close when clicking somewhere else.
@Gomez @ChristophWurst
> popover should close on clicking somewhere else

- CHANGELOG.md
- appinfo/database.xml
change email length from 64 to 255 in the database
@ChristophWurst @Gomez
> fix email length in the database

- lib/mailbox.php
Inspired by @DeepDiver1975's PR https://github.com/owncloud/mail/pull/747 I debugged the message fetching code and found out none of the IMAP servers I use have SORT capabilities. This means horde will do the sort client-side. While that's alright, looking at horde_imap.log I observed that way too much information is queried for sorting. It appears the full envelope data is fetched for sorting by date, which is useless and performance heavy.
This PR is a experiment where the sorting is done client-side by fetching message UIDs and DATEs, slicing the result and fetching the full info of that slice only.
I compared fetching the unified inbox with three accounts (two on my hoster, one is gmail).
Current master: ~2050ms
This branch: ~1550ms
Considering that ~500ms are needed for an OC request …
> fetch UIDs and DATEs of all messages and do the pagination client side

- js/views/account.js
While switching between different account's inboxes, I found myself clicking on the account name instead of the 'inbox' mailbox. Hence, I thought we could load the first mailbox of the account in that situation, which most likely is the inbox of that account.
@jancborchardt @skjnldsv what do you think?
Not sure if we should also change the cursor accordingly.
> open first mailbox when clicking the account's email address

- js/controller/foldercontroller.js
- js/views/messages.js
This is simply obsolete as we're now storing the list of messages in the folder model, which is used for the folder content view. Hence, there is no need to reset the collection explicitly (it's reset when (re)loading the folder anyway).
please review @tahaalibra @Gomez
> remove obsolete folder reset event + event handler

- js/radio.js
- js/views/app.js
- js/views/foldercontent.js
- js/views/messages.js
This enhances/replaces the previous error-prone keyboard event handling and adds support for 'j', 'k', arrow left/right navigation of messages.
Note that I chose left/right error intentionally as up/down confuses FF and should be used to scroll in long messages or the messages list.
partially fixes https://github.com/owncloud/mail/issues/160
> Enhanced keyboard event handling + new shortcuts

- bower.json
Fixes ```bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes```
> use 'mail' instead of 'Mail' for bower to prevent warning

- README.md
I followed the instructions to reset the mail app. When re-enabling the app, I got an error message "Table oc_mail_collected_addresses already exists". For a clean reinstall, it has to be dropped, too.
> Update "Resetting the app"

- css/mail.css
- js/views/messagesitem.js
- js/views/messagesview.js
As discussed @ChristophWurst – very slight gradient behind the »check messages« spinner, and using the small spinner below as well.
> add slight loading gradient, and use same spinner below

- js/service/messageservice.js
- js/views/appview.js
- js/views/messagesview.js
fixes the following bugs:
- pagination works again (next messages are added and the old ones are not removed)
- when reloading the list, some browsers scroll to the top (e.g. FF), where we now discard the first scroll event to prevent double reloading
@jancborchardt @Gomez @owncloud/mail
> fix messages pagination

- js/views/messagesview.js
Please review my beginner Backbone code :D @ChristophWurst @Gomez 
At least from testing it seems to work fine, no glitches seen yet.
> scroll to refresh even when already at top of list, fix #1588

- js/cache.js
Motivation for switching to this shorter-lived storage:
* we store sensitive information in the browser storage, which lives forever if you local storage
* if the cache is old (1d old or older) chances are high it's worthless as the messages in your folders changed already and the cached ones will be deleted anyway
* cache only speeds up page refreshes, so it doesn't really help if our AJAX calls are slow
* if we built better data structures on the client side, we don't have to cache stuff. we can simply built up a data structure of accounts, folders and messages and use the data that has already been loaded before
@LukasReschke @jancborchardt @owncloud/mail please review and tell me what you think. Closing a tab or closing the browser will clear the storage, but I could not really notice …
> use session storage instead of local storage

- js/app.js
- js/controller/accountcontroller.js
- js/controller/foldercontroller.js
- js/service/accountservice.js
- js/service/folderservice.js
- js/templates/account.html
- js/templates/newmessage.html
- js/views/account.js
- js/views/appview.js
- js/views/navigation-accounts.js
- js/views/navigation.js
- js/views/newmessage.js
- js/views/setup.js
- lib/controller/pagecontroller.php
- templates/index.php
- tests/controller/pagecontrollertest.php
* load list of accounts with index page (hidden input, recommended at http://backbonejs.org/#Collection-fetch). This reduces the time needed to load the initial data on page load.
* hide list of accounts/folders until they have finished loading and an error occurred. This also allows users to finally delete/edit accounts that are (temporarily) failing.
> Load accounts with index page

- js/require_config.js
Fix for https://github.com/owncloud/mail/issues/1163
This will use a dynamic baseUrl for require.js to make the mail app work within other app folders than apps/.
> Fix requirejs for other locations than apps/

- lib/controller/messagescontroller.php
- tests/controller/messagescontrollertest.php
@owncloud/mail easy to review :-)
Fixes 
```
Analysing nextcloud/apps/mail/lib/controller/messagescontroller.php
1 errors
line  382: Util::linkToRoute - Method of deprecated class must not be called
```
> replace Util::linkToRoute with IUrlGenerator::linkToRoute

- lib/service/htmlpurify/transformcssbackground.php
- lib/service/htmlpurify/transformimagesrc.php
Fixes
```
Analysing nextcloud/apps/mail/lib/service/htmlpurify/transformimagesrc.php
2 errors
line   66: Util::imagePath - Method of deprecated class must not be called
line   75: Util::imagePath - Method of deprecated class must not be called
```
and
```
Analysing nextcloud/apps/mail/lib/service/htmlpurify/transformcssbackground.php
1 errors
line   68: Util::imagePath - Method of deprecated class must not be called
```
> replace Util::imagePath with OCP\IURLGenerator::imagePath

- lib/controller/pagecontroller.php
- templates/index.php
- tests/controller/pagecontrollertest.php
Makes the code testable and fixed the following code checker error:
```
Analysing nextcloud/apps/mail/templates/index.php
4 errors
line   46: OCP\User::getDisplayName - Method of deprecated class must not be called
line   46: OCP\User::getUser - Method of deprecated class must not be called
line   48: OCP\Config - Static method of deprecated class must not be called
line   48: OCP\User::getUser - Method of deprecated class must not be called
```
> inject prefilled data

- js/app.js
fixes https://github.com/owncloud/mail/issues/1622
I don't know why this errror occurs now for so many people, but apparently the script is executed before the full page html has been loaded, therefore the element is not found.
@owncloud/mail @LEDfan @zeugmatis @irgendwie @Draghtnod review/test please.
@Gomez I think we should backport this fix and release it as 0.5.3
> delay app start until the page has been fully loaded
